version: "3.7"
services:
    app:
        build:
            args:
                user: oms
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: oms
        container_name: oms-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - oms

    db:
        image: mysql:8.0
        container_name: oms-db
        restart: unless-stopped
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PORT: ${DB_PORT}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker/mysql:/docker-entrypoint-initdb.d
        networks:
            - oms

    nginx:
        image: nginx:alpine
        container_name: oms-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
        networks:
            - oms

networks:
    oms:
        driver: bridge
