# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Service\:
        resource: '../src/Service/'
        public: true

    App\Service\Infrastructure\ICategoryService $categoryService: '@App\Service\CategoryService'
    App\Service\Infrastructure\ICostumerService $customerService: '@App\Service\CostumerService'
    App\Service\Infrastructure\IDiscountService $discountService: '@App\Service\DiscountService'
    App\Service\Infrastructure\IOrderService $orderService: '@App\Service\OrderService'
    App\Service\Infrastructure\IProductService $productService: '@App\Service\ProductService'

    App\EventListener\OrderProductEventListener:
        tags:
            - {
                name: 'doctrine.orm.entity_listener',
                event: 'preUpdate',
                entity: 'App\Entity\OrderProduct'
            }
            - {
                name: 'doctrine.orm.entity_listener',
                event: 'postPersist',
                entity: 'App\Entity\OrderProduct'
            }

    App\EventListener\ExceptionEventListener:
        tags:
            - {
                name: kernel.event_listener,
                event: kernel.exception
            }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones